import Link from 'next/link'
import React from 'react'

const data = {
    mariainesoscares:
    {
        name: 'María Inés Oscares',
        subtitle: 'Madre y Docente',
        slug: 'mariainesoscares',
        text: `
        Nació en la localidad de ciudadela provincia de Buenos Aires. Su familia estaba compuesta por mamá Gloria Bruzza Díaz, papá Mario Oscares Tamagno, razón por la cual corren por sus venas sangre italiana y española. Sus hermanas; Gloria la mayor y Laura la menor.
        Su mama era docente y siempre la observaba cómo preparaba sus clases, recuerda también que dibujaba muy bien y que se sentaban a ver cómo hacía las láminas para sus clases, incluso llego a ser su alumna en sexto grado. Su papá era empleado bancario y llegó a ser tesorero del banco español del río de la plata que quedaba en la localidad de Liniers
        Recuerda que los juegos en la infancia eran muy simples; su mama tenía una colección de libros de Barcelona y se imaginaba que la tapa de los libros era como ambientes de una gran casa; ponía un libro junto al otro acostados y se imaginaba que sus muñequitos tenían cada uno su habitación, jugaba con muñecas, iba a la terraza con sus hermanas y jugaban a la mancha, a la escondida, juego que también lo hacían con los chicos del barrio.
        Durante las vacaciones iba a visitar a la familia materna, qué vivía en Mercedes provincia de Buenos Aires ahí con sus primos andaba en bicicleta, visitaba el parque o iba a la pileta municipal, otros veranos iban hasta Villa Gesell donde alquilaban una casa. Comenta que fue una vida familiar muy tranquila donde no tenía demasiadas cosas materiales con que entretenerse, si recuerda cuando tenía 7 años salió la televisión en la Argentina. Fue a estudiar dibujo antes de los 12 años y también a esa edad empezó el gusto por leer; como por ejemplo Alicia en el país de las maravillas, lo leyó con muchas ganas, dice. Tenía el hábito de la lectura porque su mama y su papá también leían mucho; cada uno tenía diferentes lecturas, pero los dos leían. Recuerda también haber leído sobre historia antigua, dice que la leía como si hubiese estado leyendo un cuento de la antigüedad. Uno de los juegos que eran característicos de esa época eran los carnavales: tirarse baldazos de agua con los vecinos de enfrente o con los de la misma cuadra, se escondían a esperar que se asomaran, también jugaban con bombitas de agua, pero más que nada eran baldazos, fue algo característico y muy divertido de los carnavales en su preadolescencia además de ir al corso disfrazada cuando era más chica.
        Su papá y su mamá cantaban y entonaban los dos muy bien y en las fiestas familiares cantaba casi toda la familia. Recuerda con mucho cariño cómo cantaba junto a sus dos hermanas con su papa y mama.
        Recuerda también ver a su abuela materna sentada frente a su caballete, con la típica paleta de pintor en la mano, dando pinceladas a sus hermosos cuadros hechos sobre tela. Su casona gigante con objetos de arte, como figuras de hierro negras sosteniendo luces o figuras de mármol y hasta una jaula de bronce… piensa que de allí ha sacado su aprecio y buen gusto por las antigüedades.
        De jovencita iba al cine con toda la familia, películas como Bambi, La bella durmiente... y todas las nuevas películas de Walt Disney de aquella época.
        Empezó primer año en al Colegio Nacional de Morón, dice que “Era una nerd” así le dirían ahora. Le gustaba estudiar porque si le hacían preguntas, quería conocer las respuestas.
         Si tenía "prueba" se levantaba a las 4 de la mañana para repasar tener frescos los conocimientos. Amaba matemática, física y química. Las otras materias no le gustaban tanto, pero se sacaba buenas notas porque ser buena alumna era algo que le nacía y que nadie le pedía.
        Tuvo la lamentable pérdida de su madre, que fue internada a un año de ser detectado un tumor en la mama, y que la obligó a abandonar su 4to año de la secundaria a mediados del año 1966. 
        Se turnaban con su padre y su hermana mayor, para acompañar a su mama en la habitación en el Policlínico Bancario, su situación empeoró, falleciendo en mayo del año 1967. Ese año, pasados unos meses pudo terminar su 4to año. Finalizando el secundario en el año 1968, un año después de lo que le correspondía por la edad. Durante esa etapa siguió leyendo mucho: Amén de Jane Ayre, Cumbres Borrascosas, Ling Yutang, Ernest Hemmingay, Erich Fromm, André Maurois, clásicos de la época. También Todos los fuegos el fuego, Bestiario y Rayuela de Cortázar, El tercer ojo, que no recuerda el autor.
        Al fallecer su madre se disgrega la familia, su hermana menor se casó a los 16 años y su hermana mayor también se casó. Quedo sola con su padre. Hasta que comenzó a trabajar para poder mantenerse, porque su padre entendía que ya era mayor de 21 y no le correspondía pasarle dinero. Así fue que empezó a trabajar en algunas empresas en los sectores de administración que pagaban muy bien.
        Se reencontró con Daniel, su novio de la secundaria después de 7 años y se comprometieron durante la Peregrinación a pie de la Juventud a Luján, a las 9 de la noche, sentados en la plaza de la localidad de Merlo mientras descansaban los demás peregrinos. Se casaron el 23 de enero 1976 por civil y el 24 de enero por iglesia en la iglesia Santiago Apóstol de Haedo y como estaban anotados en el Consejo Nacional de Educación (el de la calle Pizzurno en Bs As), les salió una suplencia en la localidad de Cholila, que era un paraje perdido antes de llegar a El Bolsón, Prov. del Chubut y fue entonces que a partir de allí dieron inicia a su gran travesía de venir a poblar la Patagonia.
        En Cholila fue maestra de una sección de grado. En la escuela había solo seis docentes y el director únicamente. Les dieron a ella y su esposo, un pequeño cuartito para los dos para que allí durmieran. Recuerda que hasta llegó a bañarse en un fuentón grande, calentando agua porque en el medio de la nada no había agua caliente y fría.
         Comenta que cuando vivía en la ciudad tenía todas las comodidades y desconocía la vida de campo, pero logro adaptarse. Cree que, porque interiormente la aventura la entusiasmaba, pero además porque estaba muy bien acompañada, dice.
        Lo más cercano si querían galletitas o hablar por teléfono de larga distancia estaba a 5 km caminando por la calle de ripio hasta un cruce donde había un ACA. Allí estuvieron una semana a fines de enero del 76. Como Daniel, su esposo, tenía el título de profesor además del de maestro, les ofrecieron ir a hacerse cargo de una escuela que quedaba en medio de la provincia. Estar solos ellos allí. Para eso se trasladaron en un colectivo hasta Esquel, dónde los esperaba un supervisor escolar de apellido Ñancucheo, que los llevó en su auto cruzando la provincia de NO a SE llegando a la ciudad de Trelew donde se encontraba la Supervisión Escolar distrito Sur. Ahí firmaron los papeles de la toma de posesión de los cargos: María Inés como maestra de sección múltiple de 1ro a 3er grado y su esposo director a cargo de la otra sección múltiple de 4to a 7mo. En Trelew tomaron un micro hasta Comodoro Rivadavia. Con todos sus bártulos rumbo al nuevo destino la aldea escolar llamada Buen Pasto. Para eso debían llegar desde Comodoro hasta la localidad de Sarmiento. Y Desde allí en un Unimok del Batallón 601, que eran los padrinos de la escuela. Recuerda que el camino era puro ripio, sinuoso y entre cerros de aproximadamente 90 km. Dice que de repente llegaron a una altura donde se abría un vallecito, y ahí con techos rojos y sobre un terreno de 100 metros cuadrados estaba la escuela. Era de las llamadas del Plan quinquenal: Construcción de material, con un ala derecha destinada a la casa del director, living pequeño, cocina, dormitorio y baño. En el living una puerta los llevaba al patio de la escuela.
        Dice que esa escuela, como la de Cholila, funcionaba de septiembre/ mayo, porque los inviernos eran muy crudos. Allí tuvo un alumnito de apellido Curallán que vivía a 5 km en un lugar rodeado de arbolitos (por un pozo de agua semisurgente natural) que se veían chiquitos desde la escuela. Él iba a caballo montado a pelo (sin montura) Con los alumnos hacia caminatas a buscar en los picaderos (donde había cantidad de piedras chatas como limadas y era donde el antiguo pueblo de originarios de la zona (mapuches) hacia sus puntas de flechas)
        La escuela no tenía ni luz ni agua, cocinaba en la Histilart (cocina de hierro que funciona a leña) y se alumbraban con faroles de querosene, tenían unos en el living y el otro lo llevaban donde necesitaban ir. Calentaban agua para bañarse (porque el baño tenía bañera) en una olla grande del tipo de las del ejército. Recuerda que, para la copa de leche de los niños, una mamá que tenía dos nenes en la escuela hacia la leche todos los días con cascarilla de cacao o maicena con leche.
        María Inés como maestra convoco a la asistente social de la ciudad de Sarmiento para que fuera y dictara talleres de tejido y repostería con las señoras. Allí aprendió a hacer la crema de manteca y que podía darle color naranja con unas gotas de la cocción de la zanahoria o roja si cocinaba remolacha. Para ella toda una experiencia inédita para quien nace en la ciudad donde se compran los colorantes.
        La mesa de la cocina era un pizarrón chico en desuso, con dos caballetes. Y las mesas de luz las habían hecho con dos latas de galletitas grandes. Las latas eran de tapa redonda que las ponían de forma horizontal con la posibilidad de ahí guardar los zapatos. Aprendió a planchar con la plancha de hierro que se calentaba sobre la cocina a leña. Su vida era humilde…como la de los pobladores de la aldea que no llegaban a 100. Aprendió que pelar ojos en el ganado ovino y que no era sacarle los ojos, era cortarle la lana que no les permitía ver bien. Probó carne de guanaco, potranca y piche (especie de mulita)
        Como maestra rural invitaba a los sacerdotes de Sarmiento a ir cada 15 días a dar misa donde se celebraban bautismos o comuniones. Algunos de los pobladores estaban casados por civil y eran cristianos. Otros no.
        Recuerda que los chicos no tenían otro entretenimiento, así que los sábados iban al patio de la escuela para jugar al ping pong (la mesa era un pizarrón grande), y les enseñaban junto a su esposo Daniel a jugar a las damas y al ajedrez. En los dos años trabajando en Buen Pasto visitó en una oportunidad la Escuela Nro. 102 un Supervisor Escolar, que llegaba viajando desde Trelew. Fue la primera vez y la última que alguien supervisó la tarea escolar que allí se realizaba. Sólo hubo un seminario de capacitación para maestros de frontera en la localidad de Rio Mayo. Por ese motivo su esposo como director elevó una nota de reclamo. Por ese motivo fue el ofrecimiento de viajar a Rio Grande, a la Escuela Nro.4
        Llego junto a su esposo Daniel a Rio Grande el 13 de marzo de 1978, en avión desde Comodoro Rivadavia. Los recibió, en el viejo aeropuerto local, el Secretario de Obras Públicas del Municipio, de apellido Villanueva quien en una camioneta los llevó hasta la Escuela N4 "Remolcador Guaraní" que quedaba en al antiguo Barrio CAP (el frigorífico todavía funcionaba) y para ello se debía ir por la ruta número 3 hacia el sur, y pasando el destacamento se tomaba la ruta paralela al rio (hace un año se abrió para ir a las chacras) porque no existía el actual puente que va directo.
¡¡Ese año vivió la experiencia de la nieve y el hielo del invierno fueguino!!
Tiene Grabado en su memoria momentos de esa época como por ejemplo las voces y la música de apertura del programa que cada mañana los acompañaba en sus desayunos antes de empezar la jornada diaria.El programa era Lavando cebaduras para invitar y conocernos, que se oía por Radio Nacional Rio Grande y las voces con esa tonada tan de acá y campera eran la de Mingo Gutiérrez y la del Dr.Adrián Bitch.Inolvidables eran para María Inés esas mañanas del primer año de su vida acá en la isla
Anecdótico fue el nacimiento de su primera hija fueguina: el camino a la vera del río estaba cortado por un camión cruzado; en setiembre había mucho barro por el deshielo.Por eso cuando rompió bolsa ese 14 de setiembre la subieron a la camioneta del Sr.Solanz(que tenía radio ante una emergencia) y junto a la señora de Andrade, mamá de la escuela, tuvieron que recorrer el camino viejo paralelo al mar hasta Punta María y de allí derecho por la ruta 3 - todavía de tierra y ripio - llego justo para ingresar al quirófano y en 10 minutos nació su primogénita.Su esposo Daniel iba detrás en su primer auto un Citroën 3CV.
Ese año vivió el conflicto con Chile por las tres islas.Donde se suspendieron las clases porque en la escuela se alojaron soldados que habían llegado ante un posible enfrentamiento.El frigorífico se preparó como un lugar para retener a los soldados enemigos.
En la escuela Nro. 4 conoció a la que fue Prof.de música y folklore Sra.Graciela Balverdi y en una fiesta escolar del 10 de noviembre actuó el dúo de Rubén Baliño y Raúl Perez muy jóvenes por esos tiempos, pero con mucho brío y muy buenas voces, recuerda.
Al mudarse a la ciudad en el año 1979 se incorpora como maestra de la Escuela Nro8, en ese entonces en el Barrio Mutual, sobre calle Resistencia.Fue docente de 5°Grado turno mañana.Sulema Lodeiro fue la primera directora, y la vicedirectora María del Carmen Campos.Es año 1979 nació la segunda fueguina de la familia.
En el año 1981 tomó un cargo por la tarde en la Escuela Ceferino Namuncurá, el área primaria del Instituto Don Bosco.Nació el tercer fueguino y el director, Padre Adolfo Povalej fue el padrino de bautismo del primer varón.Allí trabajo hasta que se creó la primera Supervisión Escolar de Rio Grande, siendo la Sra.Vilma Varas nombrada para el cargo y la que la convoca para que fuera su secretaria.¡¡Fue estando allí que en el año 1983 nació el cuarto fueguino!!
Orgullosa de poder cumplir con el rol de super mamá, con amor y ternura que cada hijo le inspiraba; y orgullosa de su rol docente, con el que siempre cumplía con mucho compromiso y responsabilidad.
María Inés fue una de esas maestras que respetó al extremo con quien estaba trabajando, sea superior, colega o personal de maestranza.Pero sobre todo a los alumnos a quienes dedicada su tarea.
    En 1985 dejo de trabajar en la Supervisión porque se trasladó con su familia a la ciudad de Ushuaia por motivos de trabajo de su esposo y allí fue mamá tiempo completo hasta abril de 1986 en el que emprendieron el regreso a Rio Grande.
Ese mismo año tomo un cargo en la Escuela Nro. 14 que quedaba a una cuadra de su casa, intevu XX casa 10. Allí se desempeñó como maestra de grado, empezó con 4to grado, pero como le gustaban los más pequeños, su pedido de ser posible era que la ubicaran de 1ro a 3ro.
Siempre le gusto cantar y con los más pequeños podía captar mucho más su atención con la música.Cantaba para pedir silencio, o para cuando volvían al aula del recreo.Recuerda haber sido la voz que a capella dirigía los ensayos del himno y canciones patrias(según la fecha comenta) en la Escuela nro. 4, 8, 14, 35 y Don Bosco, escuelas donde trascurrieron sus años como docente.Cuenta que su voz nunca necesitó micrófono porque siempre fue de tener mucho volumen y un registro no de soprano sino de mezzo.Además, se dedicó a enseñar a cada grupo(la escuela completa) y decirles a los estudiantes que debían abrir la boca para que la voz se escuchara.Dice que muchos chicos no se animaban a escucharse.Cree que muchos de sus ex estudiantes se acordarán de ese pedido especial.¡¡Pero así fue que pudo lograr que las marchas se escucharan!!
Por aquellas épocas se desempeñó como auxiliar de dirección, secretaria interina, vicedirectora interina y directora suplente.En la escuela numero 14 trabajo hasta fines del 1995.
Mientras tanto en el año 1988 nacía quinta fueguina.Celeste.
Se muda con su familia a la casa que vive hasta el día de hoy, por aquellas épocas era una casa amplia para una familia de siete integrantes, está ubicada en el Barrio Mutual.Entonces al inaugurarse la escuela Nro. 35, pidió traslado por cercanía a su domicilio.La escuela numero 35 era una escuela de 2da categoría, con una directora y una secretaria, función esta última que desempeñó.Con el tiempo y al crecer la matricula pasó a ser de 1ra Categoría fue entonces que cubrió el interinato en la Vicedirección, para luego con la jubilación de la directora, tomar la Dirección interina.
De las directoras, Sulema Lodeiro, Carmen Valencia, Mabel Romeo, Amanda Cuello, Susana Favero guarda muy cálidos recuerdos.Dice, una con su impronta y su responsabilidad en la función de las que aprendió y se enriqueció en lo profesional.
Conoció muchísimas docentes por donde paso y dice no querer nombrar a ninguna porque temor de olvidarse de nombrar a alguna.También aprendió mucho de ellas en los talleres de capacitación que compartían, como así también de los cursos de capacitación para el personal jerárquico en las que participaba supervisión escolar.
Hizo el primer curso de Bibliotecología organizado por la provincia.La biblioteca siempre fue un lugar muy atractivo para ella, dice, porque considera que allí se encuentra el conocimiento de lo tanto se desconoce.Fue nombrada responsable de las prácticas realizadas en la Biblioteca Schmitt y en la biblioteca Kau Kren que recién comenzaba.Es por eso que las docentes que habían hecho el curso con ella debían poner en práctica lo aprendido.Fue también una experiencia muy enriquecedora como docente ya que podía aplicarlo con los chicos, recuerda.
También nos cuenta que en alguna oportunidad se desempeñó como Maestra de adultos suplente por cuestiones económicas.Por otro lado, como siempre estuvo ligada a la parroquia Don Bosco, junto a su esposo Daniel realizaban las charlas bautismales y pre matrimoniales, todo a pedido del Padre Adolfo.
Dice sentirse más fueguina que bonaerense ya que acá construyo su vida familiar y profesional.
Rio Grande, su gente, antiguos pobladores que conoció...la isla...le dio todo y mucho más como para tener una vida plena; cinco hijos y cinco nietos fueguinos su mayor tesoro.
        `
    }
}

function Post({ slug }) {
    return (
        <div>

            <h1>{data[slug].name}</h1>
            <h2>{data[slug].subtitle}</h2>
            <p>
                {data[slug].text.slice(0, 500)} ...
            </p>
            <Link href='/mujeres/marianinesoscares'><a href='/mujeres/marianinesoscares'>Continuar Leyendo →</a></Link>
        </div>
    )
}

export default Post
